### ISSUE TITLE
(node:459) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'giveaway' of undefined

### ISSUE THREAD

**Issue by THE-bedt** [Nuggies-bot/giveaways-example#3]
why does it say's like this error (node:459) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'giveaway' of undefined

**Comment by Assassin-1234** [comment]
please head over to https://github.com/Nuggies-bot/nuggies-npm and open an issue  **using the issue template**
