### ISSUE TITLE
Error: ReferenceError: bot is not defined

### ISSUE THREAD

**Issue by Drelaky** [Nuggies-bot/giveaways-example#5]
Hello I downloaded the code and when I started the code I got this error what could be wrong here?
![image](https://user-images.githubusercontent.com/53569746/135101254-614f2bf7-0e3a-4414-9128-e91c078e6c9f.png)

**Comment by Assassin-1234** [comment]
change it to `client` also use the [slash commands branch](https://github.com/Nuggies-bot/giveaways-example/tree/slash-commands-v13) if you want them to be slash commands
