### ISSUE TITLE
v13

### ISSUE THREAD

**Issue by Hype8585** [Nuggies-bot/giveaways-example#6]
This does not work for discord.js v13

**Comment by Assassin-1234** [comment]
it does?

**Comment by Hype8585** [comment]
Where is the code?

**Comment by Assassin-1234** [comment]
v13 and slash branch

**Comment by Hype8585** [comment]
Ya that did not work for me. I will try again and send u the error and
stuff on my pc

**Comment by Assassin-1234** [comment]
join the support server for errors. https://discord.gg/5PkRRer4pR
